### ISSUE TITLE
kafka-init cannot see brokers

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Docker#32]
Running from the current dev branch, I get the following error from kafka-init:
```
kafka-init_1               | curl: (7) Failed to connect to rest-proxy-1 port 8082: Connection refused
kafka-init_1               | Expected 3 brokers but found only 0. Waiting 32 second before retrying ...
```

**Comment by nivemaham** [comment]
@sboettcher Kafka-init by default retries to connect rest-proxy for few time. Does this still persist after all the retries?

**Comment by sboettcher** [comment]
yes the issue persists, even had it running for multiple hours.

**Comment by blootsvoets** [comment]
I've done some small tweaks on the network settings in dev. Updating the code and running
```shell
docker-compose down
./install-radar-stack.sh
```
should fix this. Warning: most of the configuration files were moved to `etc/`, please ensure that the variables from `etc/env.template` are set in `.env`.

**Comment by fnobilia** [comment]
Still not working with
`OS version: Linux ip-172-31-19-132 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
docker version: Docker version 17.04.0-ce, build 4845c56
docker-compose version: docker-compose version 1.12.0, build b31ff33`

Tested on 0ba3f8d6625205e25375d46999091e9c49bfc59f

**Comment by blootsvoets** [comment]
It seems to be some timing issue with the DNS or networks. Sometimes it works, sometimes it doesn't... I'm trying to see if it has to do with what interface the rest proxy binds to. Could you test if the updated setup in c806ae6 works?

**Comment by fnobilia** [comment]
I'm removing the dependence on the `Rest-Proxy` using the `zookeeper shell` instead.

**Comment by fnobilia** [comment]
504fb36 remove the dependences on `REST-PROXY`.

**Comment by sboettcher** [comment]
Just noticed this is still open, I think this is fixed by now...
